
spring:
  application:
    name: movie-metdata
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
server:
  port: 8002