
spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defalutZone: http://127.0.0.1:8762/eureka/
    register-with-eureka: false
    fetch-registry: false
---

spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
